#pragma once

typedef enum {
    STATUS_SUCCESS = 0,
    STATUS_INVALID_ARGUMENTS,
    STATUS_ERROR_READING_INPUT,
    STATUS_ERROR_ALLOCATING_BUFFER,
    STATUS_SNPRINTF_FAILED,
    STATUS_SPRINTF_FAILED,
    STATUS_ERROR_OPENING_FILE,
    STATUS_ERROR_CALLED_CLOSE_ON_CLOSED_FILE,
    STATUS_ERROR_CLOSE_FAILED, STATUS_ERROR_READ_FAILED, STATUS_EOF, STATUS_ERROR_BUFFER_TOO_SMALL
} Status;