#pragma once
#include <stdio.h>
#include <stdarg.h>

typedef enum {
    STATUS_SUCCESS = 0,
    STATUS_INVALID_ARGUMENTS,
    STATUS_ERROR_READING_INPUT,
    STATUS_ERROR_ALLOCATING_BUFFER,
    STATUS_SNPRINTF_FAILED,
    STATUS_SPRINTF_FAILED,
    STATUS_ERROR_OPENING_FILE,
    STATUS_ERROR_CALLED_CLOSE_ON_CLOSED_FILE,
    STATUS_ERROR_CLOSE_FAILED,
    STATUS_ERROR_READ_FAILED,
    STATUS_EOF,
    STATUS_ERROR_BUFFER_TOO_SMALL,
    STATUS_ERROR_MACRO_WITH_SAME_NAME_ALREADY_EXISTS,
    STATUS_ERROR_REALLOC_FAILED,
    STATUS_ERROR_FAILED_COPYING_NAME,
    STATUS_ERROR_USAGE_OF_MACRO_BEFORE_DEFINITION,
    STATUS_ERROR_MACRO_DEFINED_WITHOUT_A_NAME,
    STATUS_ERROR2,
    STATUS_ERROR3,
    STATUS_ERROR_MACROEND_OUTSIDE_DEFINITION,
    STATUS_ERROR_FILE_ENDED_BEFORE_CLOSING_MACRO, STATUS_ERROR_WRITE_FAILED
} Status;

void print_error(const char *format, ...);
